MONGODB_URI = "mongodb://bigdata:namabiru123!@seongjaeny.com:27017"
MONGODB_DB_NAME = "newstraderrl"
MONGODB_COLLECTION_NEWS = "news"
MONGODB_COLLECTION_OHLC = "ohlc"
MONGODB_COLLECTION_SIMULATION = "simulation"
MONGODB_COLLECTION_PORTFOLIO = "portfolio"